import { useMemo } from 'preact/hooks';

import type { DashboardData } from '../lib/data';
import { latest } from '../lib/sdmx';
import {
  bestRate,
  daysSince,
  isStale,
  splitDeposits,
  type Offer,
  type OfferBoard,
} from '../lib/offers';
import { bpsAbs, eur, formatAge, formatTerm, pct } from '../lib/format';
import { Chart, CHART_COLORS, Legend } from '../components/Chart';
import { ladderChart } from '../components/charts';
import { Callout, Card, Stat, StatRow } from '../components/ui';

/**
 * Maps an advertised term onto the MIR maturity band it belongs to, so an
 * advertised rate can be compared against the volume-weighted average for the
 * same kind of money.
 */
const BUCKETS = [
  { label: 'Instant access', mirId: 'dep_on', holds: (m: number | null) => m === null },
  { label: 'Up to 1Y', mirId: 'dep_term_le1', holds: (m: number | null) => m !== null && m <= 12 },
  { label: '1–2Y', mirId: 'dep_term_1_2', holds: (m: number | null) => m !== null && m > 12 && m <= 24 },
  { label: 'Over 2Y', mirId: 'dep_term_2p', holds: (m: number | null) => m !== null && m > 24 },
];

export function Offers({ data }: { data: DashboardData }) {
  const board = data.offers;

  if (!board || board.offers.length === 0) {
    return (
      <div class="grid">
        <Card
          span={12}
          title="Bank offers"
          sub="Advertised rates from published condition pages"
        >
          <Callout>
            No offer board has been published yet. It is generated by the{' '}
            <code>Refresh bank offers</code> workflow, which scrapes each bank&rsquo;s own condition
            page once a day and commits <code>public/data/offers.json</code>. Run it manually from
            the Actions tab to populate this panel.
          </Callout>
        </Card>
      </div>
    );
  }

  return (
    <div class="grid">
      <BestOfBoard data={data} board={board} />
      <AdvertisedVersusConcluded data={data} board={board} />
      <DepositBoard board={board} />
      <LoanBoard board={board} />
      <SourceHealth board={board} />
    </div>
  );
}

/* ------------------------------------------------------------------ */

function BestOfBoard({ data, board }: { data: DashboardData; board: OfferBoard }) {
  const { instant, term } = splitDeposits(board.offers);

  const bestInstant = bestRate(instant, 'deposit');
  const bestTerm = bestRate(term, 'deposit');
  const marketTerm = latest(data.at.get('dep_term'));
  const marketOn = latest(data.at.get('dep_on'));

  const termEdge =
    bestTerm?.rate !== undefined && bestTerm?.rate !== null && marketTerm
      ? bestTerm.rate - marketTerm.value
      : undefined;

  return (
    <Card
      span={5}
      title="The best of what is advertised"
      sub={`${board.offers.length} offers from ${new Set(board.offers.map((o) => o.provider)).size} providers`}
    >
      <StatRow>
        <Stat
          label="Best instant access"
          value={pct(bestInstant?.rate)}
          note={bestInstant?.provider}
          tone="positive"
        />
        <Stat
          label="Best fixed term"
          value={pct(bestTerm?.rate)}
          note={
            bestTerm ? `${bestTerm.provider} · ${formatTerm(bestTerm.termMonths)}` : undefined
          }
          tone="positive"
        />
      </StatRow>
      <StatRow>
        <Stat label="Market average, term" value={pct(marketTerm?.value)} note="ECB MIR, all banks" />
        <Stat label="Market average, overnight" value={pct(marketOn?.value)} note="ECB MIR, all banks" />
      </StatRow>
      <Callout>
        The best advertised term deposit pays <strong>{bpsAbs(termEdge)}</strong>{' '}
        {termEdge !== undefined && termEdge > 0 ? 'above' : 'below'} the volume-weighted average
        Austrian banks actually concluded last month. That difference is what shopping around is
        worth — and the fact that the average sits so far below the best offer is the clearest
        evidence that most savers do not.
      </Callout>
    </Card>
  );
}

/* ------------------------------------------------------------------ */

function AdvertisedVersusConcluded({
  data,
  board,
}: {
  data: DashboardData;
  board: OfferBoard;
}) {
  const rows = useMemo(
    () =>
      BUCKETS.map((bucket) => {
        const candidates = board.offers.filter(
          (o) => o.category === 'deposit' && o.rate !== null && bucket.holds(o.termMonths),
        );
        const best = candidates.reduce<Offer | undefined>(
          (top, o) => (top === undefined || (o.rate ?? 0) > (top.rate ?? 0) ? o : top),
          undefined,
        );
        return {
          label: bucket.label,
          best: best?.rate ?? null,
          provider: best?.provider,
          market: latest(data.at.get(bucket.mirId))?.value ?? null,
        };
      }),
    [board, data],
  );

  const option = useMemo(
    () =>
      ladderChart(
        rows.map((r) => r.label),
        [
          {
            name: 'Best advertised',
            values: rows.map((r) => r.best),
            color: CHART_COLORS.positive,
          },
          {
            name: 'Market average',
            values: rows.map((r) => r.market),
            color: CHART_COLORS.euroArea,
          },
        ],
      ),
    [rows],
  );

  return (
    <Card
      span={7}
      title="Advertised today versus concluded last month"
      sub="Best rate on the board against the ECB volume-weighted average, by maturity"
    >
      <Chart
        option={option}
        height={210}
        ariaLabel="Best advertised Austrian deposit rates compared with ECB average concluded rates by maturity"
      />
      <Legend
        shape="dot"
        items={[
          { label: 'Best advertised', color: CHART_COLORS.positive },
          { label: 'Market average (MIR)', color: CHART_COLORS.euroArea },
        ]}
      />
      <div class="table-wrap">
        <table class="rates compact">
          <thead>
            <tr>
              <th>Maturity</th>
              <th>Best advertised</th>
              <th>Provider</th>
              <th>Market average</th>
              <th>Spread</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.label}>
                <td>{r.label}</td>
                <td class="num">{pct(r.best)}</td>
                <td class="provider">{r.provider ?? '–'}</td>
                <td class="num">{pct(r.market)}</td>
                <td class="num delta up">
                  {r.best !== null && r.market !== null ? bpsAbs(r.best - r.market) : '–'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <Callout>
        The two series are not the same measurement, and the difference is the point. Green is a
        headline rate a bank is advertising right now, often to new money only. Grey is every euro
        actually placed last month, including the balances that never moved.
      </Callout>
    </Card>
  );
}

/* ------------------------------------------------------------------ */

function DepositBoard({ board }: { board: OfferBoard }) {
  const { instant, term } = splitDeposits(board.offers);

  return (
    <Card
      span={12}
      title="Savings and term deposit offers"
      sub="Advertised rates, read from each provider's own published condition page"
    >
      <div class="table-wrap">
        <table class="rates">
          <thead>
            <tr>
              <th>Provider</th>
              <th>Product</th>
              <th>Term</th>
              <th>Rate</th>
              <th>Minimum</th>
              <th>Conditions</th>
              <th>Checked</th>
            </tr>
          </thead>
          <tbody>
            <tr class="section-label">
              <td colSpan={7}>Instant access</td>
            </tr>
            {instant.map((o) => (
              <OfferRow key={o.id} offer={o} />
            ))}
            <tr class="section-label">
              <td colSpan={7}>Fixed term</td>
            </tr>
            {term.map((o) => (
              <OfferRow key={o.id} offer={o} />
            ))}
          </tbody>
        </table>
      </div>
      <Callout>
        Rates are shown before Austrian capital gains tax. KESt takes 25% of interest, so a
        headline 3.00% is about 2.25% in hand. Promotional rates that revert after a few months are
        labelled as such — the reverting rate is listed as its own row, because that is what the
        money earns for most of the time it sits there.
      </Callout>
    </Card>
  );
}

function OfferRow({ offer }: { offer: Offer }) {
  const stale = isStale(offer);
  const age = daysSince(offer.observedAt);

  return (
    <tr class={stale ? 'stale' : ''}>
      <td class="provider">{offer.provider}</td>
      <td>{offer.product}</td>
      <td>{formatTerm(offer.termMonths)}</td>
      <td class="num strong">{pct(offer.rate)}</td>
      <td class="num">{offer.amountMin === null ? '–' : eur(offer.amountMin)}</td>
      <td class="conditions">{offer.conditions ?? '–'}</td>
      <td class="source">
        <a href={offer.sourceUrl} target="_blank" rel="noreferrer">
          {formatAge(age)}
        </a>
        {offer.method === 'curated' ? <span class="badge">by hand</span> : null}
      </td>
    </tr>
  );
}

/* ------------------------------------------------------------------ */

function LoanBoard({ board }: { board: OfferBoard }) {
  const loans = board.offers.filter((o) => o.category === 'consumer' || o.category === 'mortgage');
  const mortgages = loans.filter((o) => o.category === 'mortgage');

  return (
    <Card
      span={12}
      title="Loan offers"
      sub="Representative examples published under the Austrian consumer credit rules"
    >
      {loans.length > 0 ? (
        <div class="table-wrap">
          <table class="rates">
            <thead>
              <tr>
                <th>Provider</th>
                <th>Product</th>
                <th>Rate type</th>
                <th>Nominal</th>
                <th>Effective</th>
                <th>Conditions</th>
                <th>Checked</th>
              </tr>
            </thead>
            <tbody>
              {loans.map((o) => (
                <tr key={o.id} class={isStale(o) ? 'stale' : ''}>
                  <td class="provider">{o.provider}</td>
                  <td>{o.product}</td>
                  <td>{o.fixationYears === 0 ? 'Variable' : 'Fixed'}</td>
                  <td class="num">{pct(o.rate)}</td>
                  <td class="num strong">{pct(o.effectiveRate)}</td>
                  <td class="conditions">{o.conditions ?? '–'}</td>
                  <td class="source">
                    <a href={o.sourceUrl} target="_blank" rel="noreferrer">
                      {formatAge(daysSince(o.observedAt))}
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : null}

      {mortgages.length === 0 ? (
        <Callout>
          <strong>There are no housing loan offers on this board, and that is the finding.</strong>{' '}
          Austrian banks publish savings rates as firm numbers but price mortgages through
          credit-scored calculators — the rate depends on the borrower, the property and the
          loan-to-value, so no comparable figure is published to scrape. Anything quoted elsewhere
          as &ldquo;the&rdquo; Austrian mortgage rate is either a broker&rsquo;s index or a
          representative example under assumptions that differ by bank. The honest answer to what
          housing loans currently cost is the ECB series on the Housing loans tab: actual concluded
          business, volume-weighted across every Austrian bank, broken down by fixation period.
        </Callout>
      ) : null}

      <Callout>
        Compare the effective rate, not the nominal one. Only the effective rate includes fees, and
        only it is defined identically across providers. The gap between the two columns is what the
        arrangement costs on top of the interest.
      </Callout>
    </Card>
  );
}

/* ------------------------------------------------------------------ */

function SourceHealth({ board }: { board: OfferBoard }) {
  return (
    <Card
      span={12}
      title="Where these numbers came from"
      sub={`Last run ${new Date(board.generatedAt).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' })}`}
    >
      <div class="table-wrap">
        <table class="rates compact">
          <thead>
            <tr>
              <th>Provider</th>
              <th>Status</th>
              <th>Page</th>
              <th>Note</th>
            </tr>
          </thead>
          <tbody>
            {board.sources.map((s) => (
              <tr key={s.url}>
                <td class="provider">{s.provider}</td>
                <td>
                  <span class={`badge status-${s.status}`}>{s.status}</span>
                </td>
                <td class="source">
                  <a href={s.url} target="_blank" rel="noreferrer">
                    {new URL(s.url).hostname.replace(/^www\./, '')}
                  </a>
                </td>
                <td class="conditions">{s.note ?? 'All expected rates found'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <Callout>
        A rate reaches this board only if a probe matched its label on the page <em>and</em> the
        value was plausible for the product. When a bank redesigns its site the probe finds nothing
        and the source shows as <span class="badge status-partial">partial</span> or{' '}
        <span class="badge status-failed">failed</span> — so a broken scrape looks broken rather
        than quietly publishing a wrong number.
      </Callout>
    </Card>
  );
}
